spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jwt_security
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
      # format_sql: true (commented out for now)
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
